apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: '{{ .Values.developerhub.instanceName }}'
  namespace: '{{ .Values.developerhub.namespaceName }}'
spec:
  application:
    appConfig:
      configMaps:
        - name: '{{ .Values.developerhub.appconfigConfigMapName }}'
          key: my.app-config.yaml
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'    
      secrets:
        - name: "secrets-rhdh"
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
    dynamicPluginsConfigMapName: '{{ .Values.developerhub.dynamicPluginsConfigMapName }}'
  database:
    enableLocalDb: true   