apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crd-instances
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 'crd-instances'
    repoURL: 'https://github.com/pablo-preciado/testing-helm-deployment.git'
    targetRevision: HEAD
    helm:
      parameters:
        - name: gitlab.clusterDomain
          value: apps.cluster-6mtl2.6mtl2.gcp.redhatworkshops.io
        - name: keycloak.hostname
          value: keycloak.apps.cluster-6mtl2.6mtl2.gcp.redhatworkshops.io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
