apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-demo-application-set
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - name: operators
            path: operators
            syncWave: "0"
            # extravars: false
          - name: prerequisites
            path: prerequisites
            syncWave: "1"
            # extravars: false
          - name: crd-instances
            path: crd-instances
            syncWave: "2"
            # extravars: true
            # helmExtraParameter1: keycloak.hostname
            # helmExtraParameterValue1: keycloak.apps.cluster-6mtl2.6mtl2.gcp.redhatworkshops.io
            # helmExtraParameter2: keycloak.hostname
            # helmExtraParameterValue2: keycloak.apps.cluster-6mtl2.6mtl2.gcp.redhatworkshops.io
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
      name: '{{name}}'
    spec:
      destination:
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: '{{path}}'
        repoURL: 'https://github.com/pablo-preciado/testing-helm-deployment.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: gitlab.clusterDomain
              value: apps.cluster-6mtl2.6mtl2.gcp.redhatworkshops.io
            - name: keycloak.hostname
              value: keycloak.apps.cluster-6mtl2.6mtl2.gcp.redhatworkshops.io
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
          limit: 10
        syncOptions:
          - CreateNamespace=true
#  templatePatch: |
#    {{- if .extravars }}
#    spec:
#      source:
#        helm:
#          parameters: 
#            - name: {{ .helmExtraParameter1 }}
#              value: {{ .helmExtraParameterValue1 }}
#            - name: {{ .helmExtraParameter2 }}
#              value: {{ .helmExtraParameterValue2 }}
#    {{- end }}