apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh2vm-demo-deploy
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: cluster.domain
          value: apps.cluster-dqxwv.dqxwv.gcp.redhatworkshops.io
    path: rhdh2vm-demo-deploy
    repoURL: 'https://github.com/pablo-preciado/testing-helm-deployment.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true