apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh2vm-demo-deploy
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: cluster.domain
          value: apps.cluster-zb6tw.zb6tw.gcp.redhatworkshops.io
        - name: github.pat
          value: https://github.com/sgutierr/catalog-entities
        - name: rhn.username
          value: sgutierr@redhat.com
        - name: rhn.password
          value: <here-goes-your-rhn-password>
        - name: rhn.poolId
          value: <here-goes-your-rhn-poolId>
        - name: rhn.clientId
          value: <here-goes-your-rhn-clientId>
        - name: rhn.clientSecret
          value: <here-goes-your-rhn-clientSecret>
        - name: automationhub.url
          value: <here-goes-your-automationhub-url>
        - name: automationhub.authUrl
          value: <here-goes-your-automationhub-authUrl>
        - name: automationhub.apiToken
          value: <here-goes-your-automationhub-apiToken>
        - name: ocp.apiUrl
          value: https://api.cluster-zb6tw.zb6tw.gcp.redhatworkshops.io:644
        - name: ocp.apiToken
          value: sha256~9d01hdkMvsQ323Ja84KK4cfM8QNJNl0EhfgartkerlE
    path: rhdh2vm-demo-deploy
    repoURL: 'https://github.com/pablo-preciado/testing-helm-deployment.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true
