kind: Secret
apiVersion: v1
metadata:
  name: '{{ .Values.keycloak.dbSecretName }}'
  namespace: '{{ .Values.keycloak.namespaceName }}'
data:
  password: '{{ .Values.keycloak.postgresPassword | b64enc }}'
  username: '{{ .Values.keycloak.postgresUsername | b64enc }}'
type: Opaque