
# Replace all the "vp7mj-vp5zd" with whatever is that value in your cluster

apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: kubernetes.io/arch=amd64
    machine.openshift.io/GPU: '0'
    machine.openshift.io/memoryMb: '16384'
    machine.openshift.io/vCPU: '4'
  resourceVersion: '24115'
  name: cluster-vp7mj-vp5zd-worker-d
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-vp7mj-vp5zd
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-vp7mj-vp5zd
      machine.openshift.io/cluster-api-machineset: cluster-vp7mj-vp5zd-worker-d
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-vp7mj-vp5zd
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-vp7mj-vp5zd-worker-d
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          machineType: n2-standard-4
          userDataSecret:
            name: worker-user-data
          deletionProtection: false
          networkInterfaces:
            - network: cluster-vp7mj-vp5zd-network
              subnetwork: cluster-vp7mj-vp5zd-worker-subnet
          credentialsSecret:
            name: gcp-cloud-credentials
          zone: europe-west4-c
          canIPForward: false
          metadata:
            creationTimestamp: null
          projectID: cluster-vp7mj
          region: europe-west4
          kind: GCPMachineProviderSpec
          disks:
            - autoDelete: true
              boot: true
              image: projects/rhcos-cloud/global/images/rhcos-416-94-202410211619-0-gcp-x86-64
              labels: {}
              sizeGb: 128
              type: pd-ssd
          tags:
            - cluster-vp7mj-vp5zd-worker
          serviceAccounts:
            - email: cluster-vp7mj-vp5zd-w@cluster-vp7mj.iam.gserviceaccount.com
              scopes:
                - 'https://www.googleapis.com/auth/cloud-platform'
          apiVersion: machine.openshift.io/v1beta1
          shieldedInstanceConfig: {}