---
kind: ConfigMap
apiVersion: v1
metadata:
  name: '{{ .Values.developerhub.dynamicPluginsConfigMapName }}'
  namespace: '{{ .Values.developerhub.namespaceName }}'
data:
  dynamic-plugins.yaml: |
    includes:
    - dynamic-plugins.default.yaml
    plugins:
    - disabled: false
      package: '@backstage/plugin-entity-feedback@0.0.0-nightly-20240325021142'
      integrity: 'sha512-T1pKqjDC5xIeZf6inq4+HqJtfk0BY7oJIKHhykZxRO5DqpTXQpEfIqDaeHl6obGRz3uOvL6k64yjxrF1o/RyFw=='
    - disabled: false
      package: '@janus-idp/backstage-scaffolder-backend-module-kubernetes@2.1.2'  
      integrity: 'sha512-cZS8rXdxg2KOi+B795LBs78Pm3i75Kao+I0eUF9Oco53tEvfgHyMyfYNHy6IV6nSkNG1HENvC3oTZRdsyUZJ7w=='   
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic       
    - disabled: false
      package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-security-insights
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
    - disabled: false
      package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-topology
    - disabled: false
      package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-module-utils-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-keycloak-backend-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-techdocs
    - disabled: false
      package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac      
    - disabled: false
      package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-quay
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-tech-radar      
    - disabled: true
      package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd
    - disabled: false
      package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-tekton
      pluginConfig:
        dynamicPlugins:
          frontend:
            janus-idp.backstage-plugin-tekton:
              mountPoints:
              - config:
                  if:
                    allOf:
                    - isTektonCIAvailable
                  layout:
                    gridColumn: 1 / -1
                    gridRowStart: 1
                importName: TektonCI
                mountPoint: entity.page.ci/cards
    - disabled: false
      package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-quay
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-plugin-tech-radar
    - disabled: false
      package: ./dynamic-plugins/dist/backstage-community-plugin-redhat-argocd      
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: '{{ .Values.developerhub.appconfigConfigMapName }}'
  namespace: '{{ .Values.developerhub.namespaceName }}'
  labels:
    app.kubernetes.io/instance: '{{ .Values.developerhub.instanceName }}'
    app.kubernetes.io/name: backstage
data:
  my.app-config.yaml: |
    app:
      baseUrl: ${BACKSTAGE_URL}
    argocd:
      appLocatorMethods:
      - instances:
        - name: main
          username: admin 
          password: ${ARGOCD_PASSWORD}    
          url: ${ARGOCD_URL}
        type: config
      waitCycles: 25
    auth:
      environment: production     
      session:
        secret: 
          'authsessionsecret' 
      providers:
        oidc:
          production:
            clientId: ${KEYCLOAK_CLIENTID}
            clientSecret: ${KEYCLOAK_CLIENTSECRET}
            metadataUrl: ${KEYCLOAK_URL}         
            prompt: auto
    csp:
      connect-src:
      - '''self'''
      - 'http:'
      - 'https:'
      - 'data:'
      img-src:
      - '''self'''
      - 'data:'
      script-src:
      - '''self'''
      - '''unsafe-inline'''
      - '''unsafe-eval'''
      script-src-elem:
      - '''self'''
      - '''unsafe-inline'''
      - '''unsafe-eval'''
    cors:
      credentials: true
      methods:
      - GET
      - POST
      - PUT
      - DELETE
      origin: https://${BACKSTAGE_URL}      
    backend:
      auth:
        keys:
        - secret: ${BACKEND_SECRET}
      baseUrl: https://${BACKSTAGE_URL}
      cors:
        origin: https://${BACKSTAGE_URL}
      database:
        connection:
          password: ${POSTGRESQL_ADMIN_PASSWORD}
          user: postgres
    catalog:
      locations:
      - rules:
        - allow:
          - Template
        target: https://github.com/sgutierr/catalog-entities/blob/main/software-templates/showcase-templates.yaml
        type: url
      - rules:
        - allow:
          - Template
        target: https://github.com/sgutierr/catalog-entities/blob/main/all.yaml
        type: url
      providers:
        default:
          kubernetesPluginRef: dev-cluster-infra
          name: multiclusterhub
          owner: group:rhdh
          schedule:
            frequency:
              seconds: 10
            timeout:
              seconds: 60
        github:
          providerId:
            catalogPath: /catalog-info.yaml
            filters:
              branch: main
            organization: janus-backstage
            schedule:
              frequency:
                minutes: 1
              timeout:
                minutes: 3
        keycloakOrg:
          default:
            baseUrl: ${KEYCLOAK_URL_CATALOG} 
            clientId: ${KEYCLOAK_CLIENTID} 
            clientSecret: ${KEYCLOAK_CLIENTSECRET} 
            loginRealm: backstage
            realm: backstage
            schedule:
              frequency:
                minutes: 1
              initialDelay:
                seconds: 15
              timeout:
                minutes: 1            
      rules:
      - allow:
        - Component
        - System
        - API
        - Resource
        - Group
        - Location
        - User
    enabled:
      argocd: true
      github: true
      githubOrg: true
      gitlab: false
      jenkins: false
      keycloak: true
      kubernetes: true
      ocm: true
      permission: false
      sonarqube: false
      techdocs: true
    integrations:
      github:
      - apps:
        - appId: ${GITHUB_APPID}
          clientId: ${GITHUB_CLIENTID}
          clientSecret: ${GITHUB_CLIENTSECRET}
          privateKey: |
          ${GITHUB_PRIVATEKEY}  
          webhookSecret: replaceme
        host: github.com
    kubernetes:
      clusterLocatorMethods:
      - clusters:
        - authProvider: serviceAccount
          name: dev-cluster-infra
          serviceAccountToken: ${K8S_SERVICE_ACCOUNT_TOKEN}
          skipTLSVerify: true
          url: ${K8S_API_URL}
        type: config
      customResources:
      - apiVersion: v1beta1
        group: tekton.dev
        plural: pipelineruns
      - apiVersion: v1beta1
        group: tekton.dev
        plural: taskruns
      - apiVersion: v1
        group: route.openshift.io
        plural: routes
      serviceLocatorMethod:
        type: singleTenant
    permission:
      enabled: false
      rbac:
        admin:
          users:
          - name: user:default/user1
    proxy:
      endpoints:
        /developer-hub:
          changeOrigin: true
          pathRewrite:
            ^/api/proxy/developer-hub/tech-radar: /gitops/janus-idp-gitops/-/raw/main/config/tech-radar.json
          secure: false
          target: https://github.com
        /quay/api:
          changeOrigin: true
          headers:
            Authorization: Bearer ${QUAY_CREDENTIALS}
            X-Requested-With: XMLHttpRequest
          secure: false
          target: https://quay.io
    quay:
      uiUrl: https://quay.io
    scaffolder: null
    signInPage: oidc   
    techdocs:
      builder: external
      generator:
        runIn: local
      publisher:
        type: local
      sanitizer:
        allowedIframeHosts:
        - www.youtube.com