---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-read-only
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - pods
      - pods/log
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - daemonsets
      - resourcequotas
      - routes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
  - verbs:
      - get
      - list
    apiGroups:
      - metrics.k8s.io
    resources:
      - pods
  - verbs:
      - get
      - list
    apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-k8s-plugin
subjects:
  - kind: ServiceAccount
    name: rhdh-operator
    namespace: '{{ .Values.developerhub.namespaceName }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-read-only
---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-sa-token
  namespace: '{{ .Values.developerhub.namespaceName }}'
  annotations:
    kubernetes.io/service-account.name: rhdh-operator
type: kubernetes.io/service-account-token