developerhub:
  namespaceName: rhdh-operator
  instanceName: developer-hub
  appConfigConfigMapName: my-backstage-appconfig-developer-hub
  appConfigConfigMapkey: my.app-config.yaml
  secretName: secrets-rhdh
  dynamicPluginsConfigMapName: my-backstage-dynamic-plugins-developer-hub
keycloak:
  instanceName: example-keycloak
  namespaceName: keycloak
cluster:
  domain: apps.cluster-wdw6r.wdw6r.gcp.redhatworkshops.io