kind: Keycloak
apiVersion: k8s.keycloak.org/v2alpha1
metadata:
  name: '{{ .Values.keycloak.instanceName }}'
  labels:
    app: sso
  namespace: '{{ .Values.keycloak.namespaceName }}'
spec:
  instances: 1
  hostname:
    hostname: keycloak.'{{ .Values.keycloak.clusterDomain }}'
  http:
    tlsSecret: '{{ .Values.keycloak.tlsSecretName }}'
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: '{{ .Values.keycloak.dbSecretName }}'
      key: username
    passwordSecret:
      name: '{{ .Values.keycloak.dbSecretName }}'
      key: password