apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user1
spec:
  profile:
    displayName: User1
    email: user1@example.com 
---    
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user2
spec:
  profile:
    displayName: User2
    email: user2@example.com 