---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: {{ .Values.keycloak.namespaceName }}
    openshift.io/display-name: {{ .Values.keycloak.namespaceName }}
  name: {{ .Values.keycloak.namespaceName }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.keycloak.operatorGroupName }}
  namespace: {{ .Values.keycloak.namespaceName }}
  annotations:
    olm.providedAPIs: Keycloak.v2alpha1.k8s.keycloak.org,KeycloakRealmImport.v2alpha1.k8s.keycloak.org  
spec:
  targetNamespaces: 
  - {{ .Values.keycloak.namespaceName }}
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.keycloak.subscriptionName }}
  namespace: {{ .Values.keycloak.namespaceName }}
spec:
  channel: stable-v26.0
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhbk-operator.v26.0.6-opr.1
  #version: 26.0.6-opr.1