kind: Job
apiVersion: batch/v1
metadata:
  name: create-secret-for-rhdh
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: resources-checker
      containers:
        - name: create-secret-for-rhdh
          image: registry.redhat.io/openshift4/ose-cli
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          command:
            - /bin/bash
            - '-c'
            - |
              ARGOCD_PASSWORD=$(oc get secret/openshift-gitops-cluster -n openshift-gitops -o jsonpath='{.data.admin\.password}' | base64 -d)
              ARGOCD_URL=$(oc get routes openshift-gitops-server -n openshift-gitops -o jsonpath='{.spec.host}')
              K8S_API_URL=$(oc whoami --show-server)
              K8S_SERVICE_ACCOUNT_TOKEN=$(oc -n rhdh-operator get secret rhdh-sa-token -o jsonpath='{.data.token }'| base64 -d)
              
              cat << EOF | oc apply -f -
              apiVersion: v1
              kind: Secret
              metadata:
                name: {{ .Values.developerhub.rhdhSecretName }}
                namespace: {{ .Values.developerhub.namespaceName }}
              stringData:
                AUTH_SESSION_SECRET: "redhat1"
                BACKSTAGE_URL: 'https://backstage.{{ .Values.cluster.domain }}'
                HOST_ALLOW: '*.{{ .Values.cluster.domain }}'
                ARGOCD_USERNAME: "admin"
                ARGOCD_PASSWORD: "${ARGOCD_PASSWORD}"
                ARGOCD_URL: "${ARGOCD_URL}"
                KEYCLOAK_REALM: "backstage" 
                KEYCLOAK_CLIENTID: "backstage"
                KEYCLOAK_CLIENTSECRET: "my-predefined-client-secret"
                KEYCLOAK_URL: "https://{{ .Values.keycloak.instanceName }}.{{ .Values.cluster.domain }}/realms/backstage"
                KEYCLOAK_URL_CATALOG: "https://{{ .Values.keycloak.instanceName }}-service.{{ .Values.keycloak.namespaceName }}.svc.cluster.local:8443"
                KEYCLOAK_CALLBACK_URL: "https://{{ .Values.keycloak.instanceName }}.{{ .Values.cluster.domain }}/api/auth/oidc/handler/frame"
                K8S_SERVICE_ACCOUNT_TOKEN: "${K8S_SERVICE_ACCOUNT_TOKEN}"
                K8S_API_URL: "${K8S_API_URL}"
                # GITHUB
                GITHUB_APPID: "CHANGE"
                GITHUB_CLIENTID: "CHANGE"
                GITHUB_CLIENTSECRET: "CHANGE"
                GITHUB_PRIVATEKEY: |
                          CHANGE
              type: Opaque
              EOF